### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by brendangibsondrip** [Skinney/elm-git-install#21]
I have just started using this module. I have created an `elm-git.json` file, and have tried to run the command, getting:

```
$ elm-git-install
/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/elm-git-install/index.js:98
  const url = new URL(giturl);
              ^

ReferenceError: URL is not defined
    at pathify (/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/elm-git-install/index.js:98:15)
    at buildUpdateChain (/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/elm-git-install/index.js:70:21)
    at ensureDependencies (/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/elm-git-install/index.js:49:16)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/elm-git-install/index.js:17:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
```

**Comment by SidneyNemzer** [comment]
URL isn't available globally until Node 10, try updating your Node version.

@Skinney Might be worth specifying the node engine version in the package.json? Although that just produces a warning when installing the package.

**Comment by brendangibsondrip** [comment]
That's the thing.  +1 for adding the node version in the README.

**Comment by robinheghan** [comment]
Reopening this so I don't forget.
